### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/Retake_Tanoa.Tanoa#2]
The whole Database part has to be coded.

**Comment by Salbei2500** [comment]
Use this command [getUnitLoadout](https://community.bistudio.com/wiki/getUnitLoadout) and the equivalent [setUnitLoadout](https://community.bistudio.com/wiki/setUnitLoadout) command.

**Comment by AdlerSalbei** [comment]
Started with 6490700

**Comment by Salbei2500** [comment]
Tested yesterday and it worked
